### ISSUE TITLE
Practica Roadmap

### ISSUE THREAD

**Issue by Aricel117** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-de-angeles#1]
[RoadMap.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-de-angeles/files/13331146/RoadMap.pdf)

**Comment by FedericoVictorianoSierra** [comment]
Calificación: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
